import process from "process";
import builtins from 'builtin-modules';
import { sassPlugin } from 'esbuild-sass-plugin';
import { copy } from 'esbuild-plugin-copy';
import svg from 'esbuild-plugin-svg';
import esbuild from 'esbuild';
import fs from 'fs';
import path from 'path';

// 定义输出目录，使用path.join来处理路径
const OUTPUT_DIR = path.join('D:/', 'My Note', '.obsidian', 'plugins', 'ink');

const renamePlugin = () => ({
	name: 'rename-plugin',
	setup(build) {
		build.onEnd(async () => {
			try {
				// 只有当文件存在时才尝试重命名
				if (fs.existsSync(path.join(OUTPUT_DIR, 'main.css'))) {
					fs.renameSync(path.join(OUTPUT_DIR, 'main.css'), path.join(OUTPUT_DIR, 'styles.css'));
				}
			} catch (e) {
				console.log('Info: No need to rename main.css to styles.css');
			}
		});
	}
});

const copyManifestPlugin = () => ({
	name: 'copy-manifest-plugin',
	setup(build) {
		build.onEnd(async () => {
			try {
				fs.copyFileSync('./manifest.json', path.join(OUTPUT_DIR, 'manifest.json'));
			} catch (e) {
				console.error('Failed to copy manifest.json to output directory:', e);
			}
			try {
				fs.copyFileSync('./manifest-beta.json', path.join(OUTPUT_DIR, 'manifest-beta.json'));
			} catch (e) {
				console.error('Failed to copy manifest-beta.json to output directory:', e);
			}
		});
	}
});

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

esbuild.build({
	banner: {
		js: banner
	},
	entryPoints: ['./src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins
	],
	// 配置模块解析，优先使用es模块格式来避免重复导入
	// 确保只使用一个版本的依赖库
	// 首先尝试ES模块格式，然后再尝试CommonJS格式
	mainFields: ['module', 'browser', 'main'],
	// 优先解析ES模块文件
	resolveExtensions: ['.ts', '.tsx', '.mjs', '.jsx', '.js', '.cjs', '.json'],
	// 确保所有tldraw相关模块都从node_modules解析，避免重复导入
	preserveSymlinks: true,
	format: 'cjs',
	watch: !prod,
	target: 'es2020',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outdir: OUTPUT_DIR,
	loader: {
		// '.png': 'file',
		// '.woff2': 'file',
		// '.json': 'file',
		// '.png': 'dataurl',
		// '.woff2': 'dataurl',
		// '.json': 'dataurl'
	},
	// assetNames: "./assets/[name]",
	// 确保tsconfig.json中的模块解析配置正确
	tsconfig: 'tsconfig.json',
	plugins: [
		sassPlugin({
			filter: /\.(s[ac]ss|css)$/
		}),
		svg(),
		copy({
			resolveFrom: 'cwd',	// 返回当前工作目录的名称
			assets: {
				from: ['./src/static/**/*'],
				to: [OUTPUT_DIR]
			}
		}),

		// 允许manifest.json存在于根目录，这是Obsidian在存储库中期望的，构建时会将其复制到dist
		copyManifestPlugin(),
		// 将main.css重命名为styles.css，因为这是obsidian期望的
		renamePlugin()
	],
	define: {
		'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development')
	}
}).catch(() => process.exit(1));


