import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules';
import { sassPlugin } from 'esbuild-sass-plugin'
import { copy } from 'esbuild-plugin-copy';
import svg from 'esbuild-plugin-svg';


// import renamePlugin from "./rename-plugin";
import fs from 'fs';
import { execSync } from 'child_process';

function detectBuildHostLanIpv4() {
	if (process.env.INK_DEBUG_SKIP_LAN_DISCOVERY === '1') return '';
	if (process.env.INK_DEBUG_LAN_IPV4) return process.env.INK_DEBUG_LAN_IPV4;
	for (const networkInterface of ['en0', 'en1']) {
		try {
			const ipv4 = execSync(`ipconfig getifaddr ${networkInterface}`, {
				encoding: 'utf8',
				stdio: ['pipe', 'pipe', 'ignore'],
			}).trim();
			if (ipv4) return ipv4;
		} catch {
			/* try next interface */
		}
	}
	return '';
}

const inkDebugLanIpv4 = detectBuildHostLanIpv4();
const inkDebugCursorSessionId = process.env.INK_DEBUG_CURSOR_SESSION_ID ?? '';
const inkDebugIngestPath = process.env.INK_DEBUG_INGEST_PATH ?? '';
if (inkDebugLanIpv4) {
	console.info(`[esbuild] INK_DEBUG_LAN_IPV4=${inkDebugLanIpv4} (baked for mobile ingest)`);
}
if (inkDebugCursorSessionId || inkDebugIngestPath) {
	console.info(
		`[esbuild] Cursor debug ingest: session=${inkDebugCursorSessionId || '(none)'} path=${inkDebugIngestPath || '(none)'}`,
	);
}

const renamePlugin = () => ({
	name: 'rename-plugin',
	setup(build) {
		build.onEnd(async () => {
			try {
				fs.renameSync('./dist/main.css', './dist/styles.css');
			} catch (e) {
				console.error('Failed to main.css to styles.css file:', e);
			}
		});
	},
});

const copyManifestPlugin = () => ({
	name: 'copy-manifest-plugin',
	setup(build) {
		build.onEnd(async () => {
			try {
				fs.copyFileSync('./manifest.json', './dist/manifest.json');
			} catch (e) {
				console.error('Failed to copy manifest.json to dist:', e);
			}
			try {
				fs.copyFileSync('./manifest-beta.json', './dist/manifest-beta.json');
			} catch (e) {
				console.error('Failed to copy manifest-beta.json to dist:', e);
			}
		});
	},
});



const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const buildMode = process.argv[2];
const prod = buildMode === 'production';
const watch = buildMode === undefined;
const emulateMobile = process.env.INK_EMULATE_MOBILE === 'true';

esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ['./src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	watch: watch,
	target: 'es2020',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outdir: './dist',
	loader: {
		// '.png': 'file',
		// '.woff2': 'file',
		// '.json': 'file',
		// '.png': 'dataurl',
		// '.woff2': 'dataurl',
		// '.json': 'dataurl',
	},
	// assetNames: "./assets/[name]",
	plugins: [
		sassPlugin({
			filter: /.(s[ac]ss|css)$/,
		}),
		svg(),
		copy({
			resolveFrom: 'cwd',	// Returns name of current working directory
			assets: {
				from: ['./src/static/**/*'],
				to: ['./dist'],
			},
		}),

		// Enables manifest.json to live in root as that's what obsidian expects in a repository, and this copies it to dist
		copyManifestPlugin(),
		// Renames main.css to styles.css as that's what obsidian expects
		renamePlugin(),
	],
	define: {
		'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development'),
		'process.env.INK_EMULATE_MOBILE': JSON.stringify(emulateMobile ? 'true' : 'false'),
		'INK_DEBUG_LAN_IPV4': JSON.stringify(inkDebugLanIpv4),
		'INK_DEBUG_CURSOR_SESSION_ID': JSON.stringify(inkDebugCursorSessionId),
		'INK_DEBUG_INGEST_PATH': JSON.stringify(inkDebugIngestPath),
	}
}).catch(() => process.exit(1));

